#!/bin/bash
#	Small playable version of game
#	Have fun!!

while :
do
	inp=""
	inc=""
	a=$((1 + RANDOM % 3))
	echo "    There are three doors, behind one of them is a"
	echo "brand new car! You have the chance to win it, if y"
	echo "ou can guess which door the car is behind...      "
	echo "                                                  "
	echo "First, we'll let you select a door! Go ahead...   "
	read inp
	while [[ "$inp" != [123] ]]
	do
		echo "    Well, we're actually gonna need you to select "
		echo "one of the doors available, 1, 2 or 3             "
		read inp
	done
	echo "    Door number $inp? An excellent choice.           "
	echo "Now I'll reveal one of the other doors...         "
	b=$a
	while [[ "$b" -eq "$inp" || "$b" -eq "$a" ]]
	do
		b=$((1 + RANDOM % 3))
	done
	echo "Door number $b! Behind which, is a goat!          "
	echo "                                                  "
	echo "Finally, before we reveal your door, I'll give you"
 	c=$b
	while [[ "$c" -eq "$inp" || "$c" -eq "$b" ]]
	do
		c=$((1 + RANDOM % 3))
	done
	echo "the option to switch your door from $inp to $c.   "
	echo "Of course, you don't have to if you are really sur"
	echo "e about your choice.                              "
	echo "Would you like to?                                "
	read inc
	while [[ "$inp" != [yYnN12] && "$inp" != [yYnN][eEoO] && "$inp" != [yY][eE][sS] ]]
	do
		echo "    Yes or No..?"
		read inc
	done
	if [[ "$inp" = [yY] || "$inp" = [yY][eE] || "$inp" = [yY][eE][sS] ]]
	then
		echo "Alright! your selection is now $c"
		inp=$c
	fi
	echo "And... behind door $inp... is..."
	if [[ "$inp" -eq "$a" ]]
	then
		echo "A brand new car!! Congratulations!"
	else
		echo "A goat! Sorry..."
	fi
	echo " "
	echo " "
	echo " "
done
