#!/bin/bash
#	Small playable version of game
#	Changable variables if you wanna change em
simMin=1
simMax=100

echo "Range of numbers is $simMin through $simMax"

while :
do
	inp=""
	a=$(($simMin + RANDOM % $simMax))
	b=$a
	while [ "$b" -eq "$a" ]
	do
		b=$(($simMin + RANDOM % $simMax))
	done
	echo "The first number is $a, and the the second is unknown"
	echo "Is the first number greater than the second?"
	read inp
	while [[ "$inp" != [yYnN12] && "$inp" != [yYnN][eEoO] && "$inp" != [yY][eE][sS] && "$inp" != ['><'] ]]
	do
		echo "Invalid input, Yes or no. (1/2, >/<, Y/n)"
		read inp
	done
	if [[ "$inp" = [yY1] || "$inp" = [yY][eE] || "$inp" = [yY][eE][sS] || "$inp" = ['>'] ]]
	then
		if [ "$a" -gt "$b" ]
		then
			echo "Correct! $a > $b, Good job!"
		else
			echo "Incorrect! $a < $b, Nice try!"
		fi
	elif [[ "$inp" = [nN2] || "$inp" = [nN][oO] || "$inp" = ['<'] ]]
	then
		if [ "$a" -lt "$b" ]
		then
			echo "Correct! $a < $b, Good job!"
		else
			echo "Incorrect! $a > $b, Nice try!"
		fi
	fi
	echo ""
done